# Generated by Django 5.2.8 on 2025-11-07 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="article_images/"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("reader", "Reader"),
                    ("editor", "Editor"),
                    ("journalist", "Journalist"),
                    ("publisher", "Publisher"),
                ],
                default="reader",
                max_length=20,
            ),
        ),
    ]
