# Generated by Django 5.2.8 on 2025-11-17 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news_app", "0005_article_is_rejected_article_rejected_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="subscribed_publishers",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={"role": "reader"},
                related_name="subscribed_readers",
                to="news_app.publisher",
            ),
        ),
    ]
