# Generated by Django 5.2.8 on 2025-11-18 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news_app", "0006_customuser_subscribed_publishers"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="independently_published",
            field=models.BooleanField(default=False),
        ),
    ]
