# Generated by Django 5.2.8 on 2025-11-18 19:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news_app", "0007_article_independently_published"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="subscribed_journalists",
            field=models.ManyToManyField(
                blank=True,
                related_name="journalist_subscribers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
