# Generated by Django 5.2.8 on 2025-11-23 12:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news_app", "0009_alter_publisherjoinrequest_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="publisher",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="publishers_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
