# Generated by Django 5.2.8 on 2025-11-15 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news_app", "0003_publisherjoinrequest"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="subscribed_publishers",
        ),
        migrations.AddField(
            model_name="customuser",
            name="subscribed_newsletters",
            field=models.ManyToManyField(
                blank=True, related_name="subscribers", to="news_app.newsletter"
            ),
        ),
    ]
