# Generated by Django 5.2.8 on 2025-11-23 11:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news_app", "0008_alter_customuser_subscribed_journalists"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="publisherjoinrequest",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterUniqueTogether(
            name="publisherjoinrequest",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="publisher",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"role": "publisher"},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owned_publishers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="publisherjoinrequest",
            name="message",
            field=models.TextField(blank=True),
        ),
        migrations.AddConstraint(
            model_name="publisherjoinrequest",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "pending")),
                fields=("user", "publisher"),
                name="unique_pending_join_request",
            ),
        ),
    ]
